allowBuilds:
  '@reown/appkit': true
  bufferutil: true
  keccak: true
  msgpackr-extract: true
  sharp: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - '@p2pdotme/sdk@1.3.6'

onlyBuiltDependencies:
  - msgpackr-extract
